language: python
dist: trusty
sudo: false
cache: pip
python: 3.5

install:
  - pip install .[ci] # Install TAF with CI deps

script:
  - pylint taf_sc
  - bandit -r taf_sc
  - pytest

after_success:
  - cd tests
  - coveralls
  - cd -
